### ISSUE TITLE
`msg="error NewHead subscription" error="notifications not supported" prefix=chain.ChainProcess`

### ISSUE THREAD

**Issue by SeaMonkey82** [shamirlabs/diva-beta-net#1]
This is all I'm seeing in the diva log once every second.

```
time="2024-08-23T19:47:51Z" level=error msg="error NewHead subscription" error="notifications not supported" prefix=chain.ChainProcess
```

**Comment by pradavc** [comment]
> This is all I'm seeing in the diva log once every second.
> 
> ```
> time="2024-08-23T19:47:51Z" level=error msg="error NewHead subscription" error="notifications not supported" prefix=chain.ChainProcess
> ```

Could you please share which Ethereum clients you use and the flags you use to run them?

**Comment by SeaMonkey82** [comment]
nethermind:
`dotnet run -c Release --no-build -- --config holesky --Init.WebSocketsEnabled=false --Init.BaseDbPath=/mnt/holesky/lighthouse-nethermind --Network.DiscoveryPort=23449 --Network.P2PPort=23449 --Network.ExternalIp "1.2.3.4" --JsonRpc.Port=8550 --JsonRpc.EnabledModules '["Consensus", "Admin", "Eth", "Subscribe", "Trace", "TxPool", "Web3", "Personal", "Proof", "Net", "Parity", "Health"]' --JsonRpc.EnginePort=8558 --JsonRpc.JwtSecretFile=/mnt/holesky/jwtsecret --JsonRpc.EngineHost "127.0.0.1"  --Network.MaxActivePeers 30 --Metrics.Enabled=true --Metrics.ExposePort=6066 --JsonRpc.Host "192.168.0.2"`

lighthouse:
`./lighthouse/target/release/lighthouse --network holesky --debug-level info beacon_node --datadir /mnt/holesky/lighthouse-nethermind --eth1 --http --metrics --execution-endpoints http://127.0.0.1:8558 --enr-udp-port=23450 --enr-tcp-port=23450 --jwt-secrets="/mnt/holesky/jwtsecret" --enr-address 1.2.3.4 --port 23450 --graffiti "lighthouse-nethermind seamonkey" --http-port 5065 --metrics-port 5061 --target-peers 30 --builder http://localhost:18550 --http-address "192.168.0.2"`

**Comment by SeaMonkey82** [comment]
validator service is failing to communicate with web3signer in the diva instance (?)

```
validator      | WRN 2024-08-23 20:26:38.920+00:00 Unable to poll validator's source          reason="Communication failed while sending/receiving request, http error [HttpConnectionError]: Could not connect to remote host" web3signer_url=http://diva:9000
```

**Comment by pradavc** [comment]
`--Init.WebSocketsEnabled=false` must be `true`

Also, unfortunately MEV boost is not supported yet.

**Comment by SeaMonkey82** [comment]
I completely missed that I had that flag on nethermind.  Whoops!
